In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
b=np.array([(1.5,2,3),(4,5,6)], dtype=float)

In [4]:
print(a)

[1 2 3]


In [5]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.arange(10,25,5)

array([10, 15, 20])

In [8]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [9]:
np.copy(a)

array([1, 2, 3])

In [10]:
h=a.copy()

In [11]:
print(h)

[1 2 3]


In [12]:
a[2]

3

In [13]:
a[0:2]

array([1, 2])

In [14]:
b[0:2,1]

array([2., 5.])

In [15]:
b[:1]

array([[1.5, 2. , 3. ]])

In [23]:
i=np.transpose(b)

In [24]:
print(i)

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]
